name: Composite cdktf workflow
description: Runs a plan or deploy action for terraform cdktf

inputs:
  aws-access-key-id:
    description: "AWS Key id"
    required: true
  aws-secret-access-key:
    description: "AWS secret key"
    required: true
  aws-region:
    description: "AWS region"
    required: true

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3

    - uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Generate module and provider bindings
      run: npx cdktf get
      shell: bash

    - name: Configure AWS Credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
