name: Deploy dev

on:
  schedule:
    - cron: "10 8 * * 1-5"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT to auth via OIDC
  contents: read # This is required for actions/checkout

jobs:
  migration:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
