name: Deploy core version
run-name: Deploy core(${{ inputs.version }}) to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true
      version:
        description: 'Version to deploy'
        type: 'string'
        required: true
      state:
        description: 'Expected infrastructure state'
        type: choice
        options:
          - running
          - restricted
        required: false
        default: running

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: Copy core-${{ inputs.version }} and workers-${{ inputs.version }} to private ECR
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        # skopeo is a tool to manage image between different registries:
        # https://github.com/containers/skopeo
      - name: Install skopeo
        run: sudo apt-get -y update && sudo apt-get -y install skopeo

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          role-session-name: GitHub_Action_deploy_core
          aws-region: ${{ vars.AWS_REGION }}

      - name: Ensure there is no migration still running
        run:
          if [[ $(aws ecs list-tasks --cluster graasp-${{ inputs.environment }} --family migrate | jq -r '.taskArns | length') -ne "0" ]]; then
          echo "# There is still a migration task running. please wait for it to complete" >> $GITHUB_STEP_SUMMARY;
          exit 1;
          fi

      - name: Copy core-${{ inputs.version }} and workers-${{ inputs.version }} to private ECR as latest
        run: |
          private_ecr_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | skopeo login --username AWS --password-stdin "$private_ecr_uri"
          for prefix in core workers; do
            image_tag=${prefix}-${{ inputs.version }}
            public_ecr_image=docker://${{ vars.AWS_PUBLIC_ECR_URI }}/graasp:$image_tag
            private_ecr_image=docker://$private_ecr_uri/graasp:${prefix}-latest
            echo "Copying $public_ecr_image to $private_ecr_image"
            skopeo --override-os linux copy "$public_ecr_image" "$private_ecr_image"
          done

  deploy:
    needs: prepare
    uses: ./.github/workflows/_deploy-infra.yml
    with:
      state: ${{ inputs.state }}
      environment: ${{ inputs.environment }}
    secrets: inherit

  restart:
    needs: deploy
    name: Force new ECS deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          role-session-name: GitHub_Action_deploy_core
          aws-region: ${{ vars.AWS_REGION }}

      - name: Force new deployment of core and workers services
        run: |
          for service in graasp workers; do
            aws ecs update-service --cluster graasp-${{ inputs.environment }} --service ${service} --force-new-deployment
          done
