name: Deploy new release
on:
  # allow to start infra of another env manually
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: environment
        required: true
      version:
        description: "Version to deploy"
        type: "string"
        required: true
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello
