name: "Apply infrastructure on env"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: environment
        required: true
      state:
        description: "Expected state, active or hibernate"
        type: choice
        options:
          - active
          - hibernate
        required: false
        default: active

jobs:
  plan:
    name: "Terraform Plan (${{ inputs.environment }})"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/plan-deploy
        with:
          isActive: false
