name: Stop infra
run-name: Stop ${{ inputs.environment }}
on:
  schedule:
    - cron: '30 16 * * 1-5'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-infra.yml
    with:
      state: 'stopped'
      environment: ${{ inputs.environment || 'dev' }}
    secrets: inherit
