name: 'Comment a Plan on a PR'

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform CDK Diff'
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare terraform
        uses: ./.github/actions/prepare-terraform
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_SECRET_AWS_ACCESS_KEY }}

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v4
        with:
          cdktfVersion: 0.20.11
          terraformVersion: 1.11.2
          mode: plan-only
          commentOnPr: true
          updateComment: false # make a new comment
          stackName: graasp-dev
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          TF_VAR_MEILISEARCH_MASTER_KEY: ${{ secrets.TF_MEILISEARCH_MASTER_KEY }}
          TF_VAR_GRAASP_DB_PASSWORD: ${{ secrets.TF_GRAASP_DB_PASSWORD }}
          TF_VAR_ETHERPAD_DB_PASSWORD: ${{ secrets.TF_ETHERPAD_DB_PASSWORD }}
          TF_VAR_UMAMI_DB_PASSWORD: ${{ secrets.TF_VAR_UMAMI_DB_PASSWORD }}
          TF_VAR_GRAASP_DB_GATEKEEPER_KEY_NAME: ${{ secrets.TF_GRAASP_DB_GATEKEEPER_KEY_NAME }}
          TF_VAR_GRAASPER_ID: ${{ vars.TF_VAR_GRAASPER_ID }}
          TF_VAR_DB_GATEKEEPER_AMI_ID: ${{ vars.TF_DB_GATEKEEPER_AMI_ID }}
          TF_VAR_DB_GATEKEEPER_INSTANCE_TYPE: ${{ vars.TF_DB_GATEKEEPER_INSTANCE_TYPE }}
          TF_VAR_APPS_PUBLISHER_ID: ${{ vars.TF_VAR_APPS_PUBLISHER_ID }}
          TF_VAR_MAILER_CONNECTION: ${{ secrets.TF_VAR_MAILER_CONNECTION }}
          TF_VAR_SENTRY_DSN: ${{ secrets.TF_VAR_SENTRY_DSN }}
          TF_VAR_OPENAI_ORG_ID: ${{ vars.TF_VAR_OPENAI_ORG_ID }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_RECAPTCHA_SECRET_KEY: ${{ secrets.TF_VAR_RECAPTCHA_SECRET_KEY }}
          TF_VAR_MEILISEARCH_REBUILD_SECRET: ${{ secrets.TF_VAR_MEILISEARCH_REBUILD_SECRET }}
          TF_VAR_GEOLOCATION_API_KEY: ${{ secrets.TF_VAR_GEOLOCATION_API_KEY }}
          TF_VAR_ETHERPAD_API_KEY: ${{ secrets.TF_VAR_ETHERPAD_API_KEY }}
          TF_VAR_H5P_ACCESS_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_KEY_ID }}
          TF_VAR_H5P_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_SECRET_KEY_ID }}
          TF_VAR_S3_ACCESS_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_KEY_ID }}
          TF_VAR_S3_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_SECRET_KEY_ID }}
          TF_VAR_APPS_JWT_SECRET: ${{ secrets.TF_VAR_APPS_JWT_SECRET }}
          TF_VAR_JWT_SECRET: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_SECURE_SESSION_SECRET_KEY: ${{ secrets.TF_VAR_SECURE_SESSION_SECRET_KEY }}
          TF_VAR_PASSWORD_RESET_JWT_SECRET: ${{ secrets.TF_VAR_PASSWORD_RESET_JWT_SECRET }}
          TF_VAR_EMAIL_CHANGE_JWT_SECRET: ${{ secrets.TF_VAR_EMAIL_CHANGE_JWT_SECRET }}
          TF_VAR_UMAMI_JWT_SECRET: ${{ secrets.TF_VAR_UMAMI_JWT_SECRET }}
