name: 'Apply infrastructure on env'
run-name: Apply "${{ inputs.state }}" on ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true
      state:
        description: 'Expected infrastructure state'
        type: choice
        options:
          - running
          - restricted
          - db-only
          - stopped
        required: false
        # default to running
        default: running

jobs:
  plan:
    name: 'Plan (${{ inputs.environment }}) - ${{ inputs.state}}'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare terraform
        uses: ./.github/actions/prepare-terraform
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_SECRET_AWS_ACCESS_KEY }}

      - name: Plan
        run: npx cdktf plan graasp-${{ inputs.environment }}
        shell: bash
        env:
          INFRA_STATE: ${{ inputs.state }}
          MAINTENANCE_HEADER_NAME: ${{ secrets.MAINTENANCE_HEADER_NAME }}
          MAINTENANCE_HEADER_SECRET: ${{ secrets.MAINTENANCE_HEADER_SECRET }}
          TF_VAR_MEILISEARCH_MASTER_KEY: ${{ secrets.TF_MEILISEARCH_MASTER_KEY }}
          TF_VAR_GRAASP_DB_PASSWORD: ${{ secrets.TF_GRAASP_DB_PASSWORD }}
          TF_VAR_ETHERPAD_DB_PASSWORD: ${{ secrets.TF_ETHERPAD_DB_PASSWORD }}
          TF_VAR_UMAMI_DB_PASSWORD: ${{ secrets.TF_VAR_UMAMI_DB_PASSWORD }}
          TF_VAR_GRAASP_DB_GATEKEEPER_KEY_NAME: ${{ secrets.TF_GRAASP_DB_GATEKEEPER_KEY_NAME }}
          TF_VAR_GRAASPER_ID: ${{ vars.TF_VAR_GRAASPER_ID }}
          TF_VAR_DB_GATEKEEPER_AMI_ID: ${{ vars.TF_DB_GATEKEEPER_AMI_ID }}
          TF_VAR_DB_GATEKEEPER_INSTANCE_TYPE: ${{ vars.TF_DB_GATEKEEPER_INSTANCE_TYPE }}
          TF_VAR_APPS_PUBLISHER_ID: ${{ vars.TF_VAR_APPS_PUBLISHER_ID }}
          TF_VAR_MAILER_CONNECTION: ${{ secrets.TF_VAR_MAILER_CONNECTION }}
          TF_VAR_SENTRY_DSN: ${{ secrets.TF_VAR_SENTRY_DSN }}
          TF_VAR_OPENAI_ORG_ID: ${{ vars.TF_VAR_OPENAI_ORG_ID }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_RECAPTCHA_SECRET_KEY: ${{ secrets.TF_VAR_RECAPTCHA_SECRET_KEY }}
          TF_VAR_MEILISEARCH_REBUILD_SECRET: ${{ secrets.TF_VAR_MEILISEARCH_REBUILD_SECRET }}
          TF_VAR_GEOLOCATION_API_KEY: ${{ secrets.TF_VAR_GEOLOCATION_API_KEY }}
          TF_VAR_ETHERPAD_API_KEY: ${{ secrets.TF_VAR_ETHERPAD_API_KEY }}
          TF_VAR_H5P_ACCESS_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_KEY_ID }}
          TF_VAR_H5P_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_SECRET_KEY_ID }}
          TF_VAR_S3_ACCESS_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_KEY_ID }}
          TF_VAR_S3_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_SECRET_KEY_ID }}
          TF_VAR_APPS_JWT_SECRET: ${{ secrets.TF_VAR_APPS_JWT_SECRET }}
          TF_VAR_JWT_SECRET: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_SECURE_SESSION_SECRET_KEY: ${{ secrets.TF_VAR_SECURE_SESSION_SECRET_KEY }}
          TF_VAR_PASSWORD_RESET_JWT_SECRET: ${{ secrets.TF_VAR_PASSWORD_RESET_JWT_SECRET }}
          TF_VAR_EMAIL_CHANGE_JWT_SECRET: ${{ secrets.TF_VAR_EMAIL_CHANGE_JWT_SECRET }}
          TF_VAR_UMAMI_JWT_SECRET: ${{ secrets.TF_VAR_UMAMI_JWT_SECRET }}

  deploy:
    needs: plan
    name: 'Deploy (${{ inputs.environment }}) - ${{ inputs.state}}'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare terraform
        uses: ./.github/actions/prepare-terraform
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_SECRET_AWS_ACCESS_KEY }}

      - name: Deploy
        run: npx cdktf deploy --auto-approve 'graasp-${{ inputs.environment }}'
        shell: bash
        env:
          INFRA_STATE: ${{ inputs.state }}
          MAINTENANCE_HEADER_NAME: ${{ secrets.MAINTENANCE_HEADER_NAME }}
          MAINTENANCE_HEADER_SECRET: ${{ secrets.MAINTENANCE_HEADER_SECRET }}
          TF_VAR_MEILISEARCH_MASTER_KEY: ${{ secrets.TF_MEILISEARCH_MASTER_KEY }}
          TF_VAR_GRAASP_DB_PASSWORD: ${{ secrets.TF_GRAASP_DB_PASSWORD }}
          TF_VAR_ETHERPAD_DB_PASSWORD: ${{ secrets.TF_ETHERPAD_DB_PASSWORD }}
          TF_VAR_UMAMI_DB_PASSWORD: ${{ secrets.TF_VAR_UMAMI_DB_PASSWORD }}
          TF_VAR_GRAASP_DB_GATEKEEPER_KEY_NAME: ${{ secrets.TF_GRAASP_DB_GATEKEEPER_KEY_NAME }}
          TF_VAR_GRAASPER_ID: ${{ vars.TF_VAR_GRAASPER_ID }}
          TF_VAR_DB_GATEKEEPER_AMI_ID: ${{ vars.TF_DB_GATEKEEPER_AMI_ID }}
          TF_VAR_DB_GATEKEEPER_INSTANCE_TYPE: ${{ vars.TF_DB_GATEKEEPER_INSTANCE_TYPE }}
          TF_VAR_APPS_PUBLISHER_ID: ${{ vars.TF_VAR_APPS_PUBLISHER_ID }}
          TF_VAR_MAILER_CONNECTION: ${{ secrets.TF_VAR_MAILER_CONNECTION }}
          TF_VAR_SENTRY_DSN: ${{ secrets.TF_VAR_SENTRY_DSN }}
          TF_VAR_OPENAI_ORG_ID: ${{ vars.TF_VAR_OPENAI_ORG_ID }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_RECAPTCHA_SECRET_KEY: ${{ secrets.TF_VAR_RECAPTCHA_SECRET_KEY }}
          TF_VAR_MEILISEARCH_REBUILD_SECRET: ${{ secrets.TF_VAR_MEILISEARCH_REBUILD_SECRET }}
          TF_VAR_GEOLOCATION_API_KEY: ${{ secrets.TF_VAR_GEOLOCATION_API_KEY }}
          TF_VAR_ETHERPAD_API_KEY: ${{ secrets.TF_VAR_ETHERPAD_API_KEY }}
          TF_VAR_H5P_ACCESS_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_KEY_ID }}
          TF_VAR_H5P_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_H5P_ACCESS_SECRET_KEY_ID }}
          TF_VAR_S3_ACCESS_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_KEY_ID }}
          TF_VAR_S3_ACCESS_SECRET_KEY_ID: ${{ secrets.TF_VAR_S3_ACCESS_SECRET_KEY_ID }}
          TF_VAR_APPS_JWT_SECRET: ${{ secrets.TF_VAR_APPS_JWT_SECRET }}
          TF_VAR_JWT_SECRET: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_SECURE_SESSION_SECRET_KEY: ${{ secrets.TF_VAR_SECURE_SESSION_SECRET_KEY }}
          TF_VAR_PASSWORD_RESET_JWT_SECRET: ${{ secrets.TF_VAR_PASSWORD_RESET_JWT_SECRET }}
          TF_VAR_EMAIL_CHANGE_JWT_SECRET: ${{ secrets.TF_VAR_EMAIL_CHANGE_JWT_SECRET }}
          TF_VAR_UMAMI_JWT_SECRET: ${{ secrets.TF_VAR_UMAMI_JWT_SECRET }}
