name: Start infra
on:
  schedule:
    - cron: "30 6 * * 1-5"
  # allow to start infra of another env manually
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: environment
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: "Deploy infra in running state to ${{ inputs.environment || 'dev' }} environment"
    environment: ${{ inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Infra
        uses: ./.github/actions/deploy-infra
        with:
          state: "running"
          environment: ${{ inputs.environment || 'dev' }}
          aws-role-to-assume: ${{ secrets.TF_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_SECRET_AWS_ACCESS_KEY }}
          maintenance-header-name: ${{ secrets.MAINTENANCE_HEADER_NAME }}
          maintenance-header-secret: ${{ secrets.MAINTENANCE_HEADER_SECRET }}
          meilisearch-master-key: ${{ secrets.TF_MEILISEARCH_MASTER_KEY }}
          graasp-db-password: ${{ secrets.TF_GRAASP_DB_PASSWORD }}
          etherpad-db-password: ${{ secrets.TF_ETHERPAD_DB_PASSWORD }}
          umami-db-password: ${{ secrets.TF_VAR_UMAMI_DB_PASSWORD }}
          graasp-db-gatekeeper-key-name: ${{ secrets.TF_GRAASP_DB_GATEKEEPER_KEY_NAME }}
          graasper-id: ${{ vars.TF_VAR_GRAASPER_ID }}
          gatekeeper-ami-id: ${{ vars.TF_DB_GATEKEEPER_AMI_ID }}
          gatekeeper-instance-type: ${{ vars.TF_DB_GATEKEEPER_INSTANCE_TYPE }}
          apps-publisher-id: ${{ vars.TF_VAR_APPS_PUBLISHER_ID }}
          mailer-connection: ${{ secrets.TF_VAR_MAILER_CONNECTION }}
          sentry_dsn: ${{ secrets.TF_VAR_SENTRY_DSN }}
          openai_org_id: ${{ vars.TF_VAR_OPENAI_ORG_ID }}
          openai_api_key: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          recaptcha_secret_key: ${{ secrets.TF_VAR_RECAPTCHA_SECRET_KEY }}
          meilisearch_rebuild_secret: ${{ secrets.TF_VAR_MEILISEARCH_REBUILD_SECRET }}
          geolocation_api_key: ${{ secrets.TF_VAR_GEOLOCATION_API_KEY }}
          etherpad_api_key: ${{ secrets.TF_VAR_ETHERPAD_API_KEY }}
          h5p_access_key_id: ${{ secrets.TF_VAR_H5P_ACCESS_KEY_ID }}
          h5p_access_secret_key_id: ${{ secrets.TF_VAR_H5P_ACCESS_SECRET_KEY_ID }}
          s3_access_key_id: ${{ secrets.TF_VAR_S3_ACCESS_KEY_ID }}
          s3_access_secret_key_id: ${{ secrets.TF_VAR_S3_ACCESS_SECRET_KEY_ID }}
          apps_jwt_secret: ${{ secrets.TF_VAR_APPS_JWT_SECRET }}
          jwt_secret: ${{ secrets.TF_VAR_JWT_SECRET }}
          secure_session_secret_key: ${{ secrets.TF_VAR_SECURE_SESSION_SECRET_KEY }}
          password_reset_jwt_secret: ${{ secrets.TF_VAR_PASSWORD_RESET_JWT_SECRET }}
          email_change_jwt_secret: ${{ secrets.TF_VAR_EMAIL_CHANGE_JWT_SECRET }}
          umami_jwt_secret: ${{ secrets.TF_VAR_UMAMI_JWT_SECRET }}
