name: Start infra
run-name: Start ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-infra.yml
    with:
      state: 'running'
      environment: ${{ inputs.environment }}
    secrets: inherit
